apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

name: opus

nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000 #nodePort set here
    hostPort: 5432
    # optional: set the bind address on the host
    # 0.0.0.0 is the current default
    listenAddress: "0.0.0.0"    
    protocol: TCP
  
  - containerPort: 31000 #nodePort set here
    hostPort: 8080
    # optional: set the bind address on the host
    # 0.0.0.0 is the current default
    listenAddress: "0.0.0.0"    
    protocol: TCP

- role: worker
  labels:
    type: worker1
  extraMounts:
    - hostPath: /mnt/data
      containerPath: /mnt/data

- role: worker
  labels:
    type: worker2
  extraMounts:
    - hostPath: /mnt/data
      containerPath: /mnt/data
  