apiVersion: v1
kind: Secret
metadata:
    name: rocket-secrets-toml
    namespace: projeto
type: Opaque

stringData:
    Rocket-toml: |
        
        [default]
        secret_key = "OUxCcJgoUTVr8BSdCPFukC2XErwqXmctHEy5oYVKAi8="
        
        [default.databases.database]
        url = "postgresql://giovanna:very_secure_pass0@postgres-svc/projeto-labbd"